Repository KiiChain/kiichain, pull requests merged in 2025-02, with the labels that each got.

#24 Bad mint panic (Websoft #3)
  cmd/kiichaind/cmd/blocktest.go
  cmd/kiichaind/cmd/ethreplay.go
  x/mint/keeper/hooks.go
  x/mint/keeper/hooks_test.go
  x/mint/keeper/keeper.go
  x/mint/keeper/keeper_test.go
  x/mint/types/minter.go
  x/mint/types/minter_test.go
Labels: consensus-breaking

#26 Fix unchecked fee (Websoft #9)
  x/evm/keeper/keeper.go
  x/evm/state/state_test.go
  x/evm/state/statedb.go
Labels: not-breaking

#25 Fix EVM codecs (Websoft #10)
  x/evm/types/codec.go
  x/evm/types/message_evm_transaction_test.go
Labels: not-breaking

#28 Create query server and params getters on keeper
  proto/oracle/query.proto
  x/oracle/keeper/keeper.go
  x/oracle/keeper/msg.server.go
  x/oracle/keeper/params.go
  x/oracle/keeper/query.server.go
  x/oracle/types/params.pb.go
  x/oracle/types/query.pb.go
  x/oracle/types/query.pb.gw.go
  x/oracle/types/snapshots.go
  x/oracle/types/vote.go
Labels: enhancement

#32 Protect mint (Websoft #4)
  proto/mint/v1beta1/mint.proto
  x/mint/gov.go
  x/mint/keeper/hooks_test.go
  x/mint/keeper/inflation.go
  x/mint/keeper/inflation_test.go
  x/mint/keeper/migrations.go
  x/mint/keeper/migrations_test.go
  x/mint/migrations/v4.go
  x/mint/migrations/v4_test.go
  x/mint/module.go
  x/mint/module_test.go
  x/mint/simulation/genesis.go
  x/mint/types/expected_keepers.go
  x/mint/types/mint.pb.go
  x/mint/types/minter.go
  x/mint/types/params.go
  x/mint/types/params_test.go
Labels: consensus-breaking
